// Runs after `next build` (static export to /out). Walks every file that was
// actually produced and writes out/sw.js with a precache list, so the app is
// fully installable and works with zero network connectivity afterward.
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const OUT_DIR = path.resolve(__dirname, "../out");

function walk(dir, base = "") {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  let files = [];
  for (const entry of entries) {
    const abs = path.join(dir, entry.name);
    const rel = base + "/" + entry.name;
    if (entry.isDirectory()) {
      files = files.concat(walk(abs, rel));
    } else {
      files.push(rel);
    }
  }
  return files;
}

const files = walk(OUT_DIR).map((f) => f.split(path.sep).join("/"));
// URL-encode each path segment (filenames can contain [ ] characters from Turbopack chunk names)
const urls = files.map((f) => f.split("/").map(encodeURIComponent).join("/"));

const hash = crypto.createHash("sha1").update(urls.sort().join("\n")).digest("hex").slice(0, 10);
const cacheName = `aras-zanjan-press-advisor-${hash}`;

const swSource = `// Auto-generated by scripts/generate-sw.js — do not edit by hand.
const CACHE_NAME = ${JSON.stringify(cacheName)};
const PRECACHE_URLS = ${JSON.stringify(urls)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) =>
      Promise.allSettled(PRECACHE_URLS.map((url) => cache.add(url)))
    ).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((names) =>
      Promise.all(names.filter((n) => n !== CACHE_NAME).map((n) => caches.delete(n)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;

  event.respondWith(
    caches.match(req).then((cached) => {
      if (cached) return cached;
      return fetch(req)
        .then((res) => {
          if (res && res.ok) {
            const clone = res.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(req, clone));
          }
          return res;
        })
        .catch(() => {
          if (req.mode === "navigate") return caches.match("/index.html");
          return caches.match(req);
        });
    })
  );
});
`;

fs.writeFileSync(path.join(OUT_DIR, "sw.js"), swSource, "utf8");
console.log(`sw.js written — cache "${cacheName}" precaching ${urls.length} files`);
